#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Du_Toan_Xay_Dung.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Construction_Estimating")]
	public partial class DataDTXDDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertArea(Area instance);
    partial void UpdateArea(Area instance);
    partial void DeleteArea(Area instance);
    partial void InsertUserWork(UserWork instance);
    partial void UpdateUserWork(UserWork instance);
    partial void DeleteUserWork(UserWork instance);
    partial void InsertBuilding(Building instance);
    partial void UpdateBuilding(Building instance);
    partial void DeleteBuilding(Building instance);
    partial void InsertBuildingItem(BuildingItem instance);
    partial void UpdateBuildingItem(BuildingItem instance);
    partial void DeleteBuildingItem(BuildingItem instance);
    partial void InsertConstructionMaterial(ConstructionMaterial instance);
    partial void UpdateConstructionMaterial(ConstructionMaterial instance);
    partial void DeleteConstructionMaterial(ConstructionMaterial instance);
    partial void InsertImages_Url(Images_Url instance);
    partial void UpdateImages_Url(Images_Url instance);
    partial void DeleteImages_Url(Images_Url instance);
    partial void InsertNormDetail(NormDetail instance);
    partial void UpdateNormDetail(NormDetail instance);
    partial void DeleteNormDetail(NormDetail instance);
    partial void InsertNormWork(NormWork instance);
    partial void UpdateNormWork(NormWork instance);
    partial void DeleteNormWork(NormWork instance);
    partial void InsertUnitPrice(UnitPrice instance);
    partial void UpdateUnitPrice(UnitPrice instance);
    partial void DeleteUnitPrice(UnitPrice instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    #endregion
		
		public DataDTXDDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Construction_EstimatingConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataDTXDDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDTXDDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDTXDDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDTXDDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Area> Areas
		{
			get
			{
				return this.GetTable<Area>();
			}
		}
		
		public System.Data.Linq.Table<UserWork> UserWorks
		{
			get
			{
				return this.GetTable<UserWork>();
			}
		}
		
		public System.Data.Linq.Table<Building> Buildings
		{
			get
			{
				return this.GetTable<Building>();
			}
		}
		
		public System.Data.Linq.Table<BuildingItem> BuildingItems
		{
			get
			{
				return this.GetTable<BuildingItem>();
			}
		}
		
		public System.Data.Linq.Table<ConstructionMaterial> ConstructionMaterials
		{
			get
			{
				return this.GetTable<ConstructionMaterial>();
			}
		}
		
		public System.Data.Linq.Table<Images_Url> Images_Urls
		{
			get
			{
				return this.GetTable<Images_Url>();
			}
		}
		
		public System.Data.Linq.Table<NormDetail> NormDetails
		{
			get
			{
				return this.GetTable<NormDetail>();
			}
		}
		
		public System.Data.Linq.Table<NormWork> NormWorks
		{
			get
			{
				return this.GetTable<NormWork>();
			}
		}
		
		public System.Data.Linq.Table<UnitPrice> UnitPrices
		{
			get
			{
				return this.GetTable<UnitPrice>();
			}
		}
		
		public System.Data.Linq.Table<UnitPrice_Area> UnitPrice_Areas
		{
			get
			{
				return this.GetTable<UnitPrice_Area>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Area")]
	public partial class Area : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private string _Name;
		
		private string _Address;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    #endregion
		
		public Area()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(500)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(500)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserWorks")]
	public partial class UserWork : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _BuildingItem_ID;
		
		private long _ID;
		
		private string _UserWork_ID;
		
		private string _NormWork_ID;
		
		private string _Name;
		
		private string _Unit_Measure;
		
		private decimal _Amount_Work;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBuildingItem_IDChanging(long value);
    partial void OnBuildingItem_IDChanged();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnUserWork_IDChanging(string value);
    partial void OnUserWork_IDChanged();
    partial void OnNormWork_IDChanging(string value);
    partial void OnNormWork_IDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnUnit_MeasureChanging(string value);
    partial void OnUnit_MeasureChanged();
    partial void OnAmount_WorkChanging(decimal value);
    partial void OnAmount_WorkChanged();
    #endregion
		
		public UserWork()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuildingItem_ID", DbType="BigInt NOT NULL")]
		public long BuildingItem_ID
		{
			get
			{
				return this._BuildingItem_ID;
			}
			set
			{
				if ((this._BuildingItem_ID != value))
				{
					this.OnBuildingItem_IDChanging(value);
					this.SendPropertyChanging();
					this._BuildingItem_ID = value;
					this.SendPropertyChanged("BuildingItem_ID");
					this.OnBuildingItem_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserWork_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserWork_ID
		{
			get
			{
				return this._UserWork_ID;
			}
			set
			{
				if ((this._UserWork_ID != value))
				{
					this.OnUserWork_IDChanging(value);
					this.SendPropertyChanging();
					this._UserWork_ID = value;
					this.SendPropertyChanged("UserWork_ID");
					this.OnUserWork_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NormWork_ID", DbType="NVarChar(50)")]
		public string NormWork_ID
		{
			get
			{
				return this._NormWork_ID;
			}
			set
			{
				if ((this._NormWork_ID != value))
				{
					this.OnNormWork_IDChanging(value);
					this.SendPropertyChanging();
					this._NormWork_ID = value;
					this.SendPropertyChanged("NormWork_ID");
					this.OnNormWork_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(3000) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit_Measure", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Unit_Measure
		{
			get
			{
				return this._Unit_Measure;
			}
			set
			{
				if ((this._Unit_Measure != value))
				{
					this.OnUnit_MeasureChanging(value);
					this.SendPropertyChanging();
					this._Unit_Measure = value;
					this.SendPropertyChanged("Unit_Measure");
					this.OnUnit_MeasureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount_Work", DbType="Decimal(18,0) NOT NULL")]
		public decimal Amount_Work
		{
			get
			{
				return this._Amount_Work;
			}
			set
			{
				if ((this._Amount_Work != value))
				{
					this.OnAmount_WorkChanging(value);
					this.SendPropertyChanging();
					this._Amount_Work = value;
					this.SendPropertyChanged("Amount_Work");
					this.OnAmount_WorkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Building")]
	public partial class Building : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private string _Email;
		
		private string _Name;
		
		private string _Description;
		
		private string _Address;
		
		private decimal _Sum;
		
		private EntitySet<BuildingItem> _BuildingItems;
		
		private EntitySet<Images_Url> _Images_Urls;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnSumChanging(decimal value);
    partial void OnSumChanged();
    #endregion
		
		public Building()
		{
			this._BuildingItems = new EntitySet<BuildingItem>(new Action<BuildingItem>(this.attach_BuildingItems), new Action<BuildingItem>(this.detach_BuildingItems));
			this._Images_Urls = new EntitySet<Images_Url>(new Action<Images_Url>(this.attach_Images_Urls), new Action<Images_Url>(this.detach_Images_Urls));
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(2000) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(2000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(1000)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sum", DbType="Decimal(18,0) NOT NULL")]
		public decimal Sum
		{
			get
			{
				return this._Sum;
			}
			set
			{
				if ((this._Sum != value))
				{
					this.OnSumChanging(value);
					this.SendPropertyChanging();
					this._Sum = value;
					this.SendPropertyChanged("Sum");
					this.OnSumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Building_BuildingItem", Storage="_BuildingItems", ThisKey="ID", OtherKey="Building_ID")]
		public EntitySet<BuildingItem> BuildingItems
		{
			get
			{
				return this._BuildingItems;
			}
			set
			{
				this._BuildingItems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Building_Images_Url", Storage="_Images_Urls", ThisKey="ID", OtherKey="Building_ID")]
		public EntitySet<Images_Url> Images_Urls
		{
			get
			{
				return this._Images_Urls;
			}
			set
			{
				this._Images_Urls.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Building", Storage="_User", ThisKey="Email", OtherKey="Email", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.Buildings.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.Buildings.Add(this);
						this._Email = value.Email;
					}
					else
					{
						this._Email = default(string);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BuildingItems(BuildingItem entity)
		{
			this.SendPropertyChanging();
			entity.Building = this;
		}
		
		private void detach_BuildingItems(BuildingItem entity)
		{
			this.SendPropertyChanging();
			entity.Building = null;
		}
		
		private void attach_Images_Urls(Images_Url entity)
		{
			this.SendPropertyChanging();
			entity.Building = this;
		}
		
		private void detach_Images_Urls(Images_Url entity)
		{
			this.SendPropertyChanging();
			entity.Building = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BuildingItems")]
	public partial class BuildingItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private long _Building_ID;
		
		private string _Name;
		
		private string _Description;
		
		private decimal _Sum;
		
		private EntityRef<Building> _Building;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnBuilding_IDChanging(long value);
    partial void OnBuilding_IDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnSumChanging(decimal value);
    partial void OnSumChanged();
    #endregion
		
		public BuildingItem()
		{
			this._Building = default(EntityRef<Building>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Building_ID", DbType="BigInt NOT NULL")]
		public long Building_ID
		{
			get
			{
				return this._Building_ID;
			}
			set
			{
				if ((this._Building_ID != value))
				{
					if (this._Building.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBuilding_IDChanging(value);
					this.SendPropertyChanging();
					this._Building_ID = value;
					this.SendPropertyChanged("Building_ID");
					this.OnBuilding_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(2000) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(2000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sum", DbType="Decimal(18,3) NOT NULL")]
		public decimal Sum
		{
			get
			{
				return this._Sum;
			}
			set
			{
				if ((this._Sum != value))
				{
					this.OnSumChanging(value);
					this.SendPropertyChanging();
					this._Sum = value;
					this.SendPropertyChanged("Sum");
					this.OnSumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Building_BuildingItem", Storage="_Building", ThisKey="Building_ID", OtherKey="ID", IsForeignKey=true)]
		public Building Building
		{
			get
			{
				return this._Building.Entity;
			}
			set
			{
				Building previousValue = this._Building.Entity;
				if (((previousValue != value) 
							|| (this._Building.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Building.Entity = null;
						previousValue.BuildingItems.Remove(this);
					}
					this._Building.Entity = value;
					if ((value != null))
					{
						value.BuildingItems.Add(this);
						this._Building_ID = value.ID;
					}
					else
					{
						this._Building_ID = default(long);
					}
					this.SendPropertyChanged("Building");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ConstructionMaterials")]
	public partial class ConstructionMaterial : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _Key_ConstructionMaterials;
		
		private string _Key_UserWork;
		
		private string _Name;
		
		private string _Unit_Measure;
		
		private decimal _Numbers;
		
		private decimal _Price;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnKey_ConstructionMaterialsChanging(string value);
    partial void OnKey_ConstructionMaterialsChanged();
    partial void OnKey_UserWorkChanging(string value);
    partial void OnKey_UserWorkChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnUnit_MeasureChanging(string value);
    partial void OnUnit_MeasureChanged();
    partial void OnNumbersChanging(decimal value);
    partial void OnNumbersChanged();
    partial void OnPriceChanging(decimal value);
    partial void OnPriceChanged();
    #endregion
		
		public ConstructionMaterial()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Key_ConstructionMaterials", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Key_ConstructionMaterials
		{
			get
			{
				return this._Key_ConstructionMaterials;
			}
			set
			{
				if ((this._Key_ConstructionMaterials != value))
				{
					this.OnKey_ConstructionMaterialsChanging(value);
					this.SendPropertyChanging();
					this._Key_ConstructionMaterials = value;
					this.SendPropertyChanged("Key_ConstructionMaterials");
					this.OnKey_ConstructionMaterialsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Key_UserWork", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Key_UserWork
		{
			get
			{
				return this._Key_UserWork;
			}
			set
			{
				if ((this._Key_UserWork != value))
				{
					this.OnKey_UserWorkChanging(value);
					this.SendPropertyChanging();
					this._Key_UserWork = value;
					this.SendPropertyChanged("Key_UserWork");
					this.OnKey_UserWorkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(2000) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit_Measure", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Unit_Measure
		{
			get
			{
				return this._Unit_Measure;
			}
			set
			{
				if ((this._Unit_Measure != value))
				{
					this.OnUnit_MeasureChanging(value);
					this.SendPropertyChanging();
					this._Unit_Measure = value;
					this.SendPropertyChanged("Unit_Measure");
					this.OnUnit_MeasureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numbers", DbType="Decimal(18,3) NOT NULL")]
		public decimal Numbers
		{
			get
			{
				return this._Numbers;
			}
			set
			{
				if ((this._Numbers != value))
				{
					this.OnNumbersChanging(value);
					this.SendPropertyChanging();
					this._Numbers = value;
					this.SendPropertyChanged("Numbers");
					this.OnNumbersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(18,3) NOT NULL")]
		public decimal Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Images_Url")]
	public partial class Images_Url : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private long _Building_ID;
		
		private string _Url;
		
		private EntityRef<Building> _Building;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnBuilding_IDChanging(long value);
    partial void OnBuilding_IDChanged();
    partial void OnUrlChanging(string value);
    partial void OnUrlChanged();
    #endregion
		
		public Images_Url()
		{
			this._Building = default(EntityRef<Building>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Building_ID", DbType="BigInt NOT NULL")]
		public long Building_ID
		{
			get
			{
				return this._Building_ID;
			}
			set
			{
				if ((this._Building_ID != value))
				{
					if (this._Building.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBuilding_IDChanging(value);
					this.SendPropertyChanging();
					this._Building_ID = value;
					this.SendPropertyChanged("Building_ID");
					this.OnBuilding_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="NVarChar(2000) NOT NULL", CanBeNull=false)]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this.OnUrlChanging(value);
					this.SendPropertyChanging();
					this._Url = value;
					this.SendPropertyChanged("Url");
					this.OnUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Building_Images_Url", Storage="_Building", ThisKey="Building_ID", OtherKey="ID", IsForeignKey=true)]
		public Building Building
		{
			get
			{
				return this._Building.Entity;
			}
			set
			{
				Building previousValue = this._Building.Entity;
				if (((previousValue != value) 
							|| (this._Building.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Building.Entity = null;
						previousValue.Images_Urls.Remove(this);
					}
					this._Building.Entity = value;
					if ((value != null))
					{
						value.Images_Urls.Add(this);
						this._Building_ID = value.ID;
					}
					else
					{
						this._Building_ID = default(long);
					}
					this.SendPropertyChanged("Building");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NormDetails")]
	public partial class NormDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private string _NormWork_ID;
		
		private string _UnitPrice_ID;
		
		private decimal _Numbers;
		
		private EntityRef<NormWork> _NormWork;
		
		private EntityRef<UnitPrice> _UnitPrice;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnNormWork_IDChanging(string value);
    partial void OnNormWork_IDChanged();
    partial void OnUnitPrice_IDChanging(string value);
    partial void OnUnitPrice_IDChanged();
    partial void OnNumbersChanging(decimal value);
    partial void OnNumbersChanged();
    #endregion
		
		public NormDetail()
		{
			this._NormWork = default(EntityRef<NormWork>);
			this._UnitPrice = default(EntityRef<UnitPrice>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NormWork_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NormWork_ID
		{
			get
			{
				return this._NormWork_ID;
			}
			set
			{
				if ((this._NormWork_ID != value))
				{
					if (this._NormWork.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNormWork_IDChanging(value);
					this.SendPropertyChanging();
					this._NormWork_ID = value;
					this.SendPropertyChanged("NormWork_ID");
					this.OnNormWork_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitPrice_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UnitPrice_ID
		{
			get
			{
				return this._UnitPrice_ID;
			}
			set
			{
				if ((this._UnitPrice_ID != value))
				{
					if (this._UnitPrice.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUnitPrice_IDChanging(value);
					this.SendPropertyChanging();
					this._UnitPrice_ID = value;
					this.SendPropertyChanged("UnitPrice_ID");
					this.OnUnitPrice_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numbers", DbType="Decimal(18,3) NOT NULL")]
		public decimal Numbers
		{
			get
			{
				return this._Numbers;
			}
			set
			{
				if ((this._Numbers != value))
				{
					this.OnNumbersChanging(value);
					this.SendPropertyChanging();
					this._Numbers = value;
					this.SendPropertyChanged("Numbers");
					this.OnNumbersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NormWork_NormDetail", Storage="_NormWork", ThisKey="NormWork_ID", OtherKey="ID", IsForeignKey=true)]
		public NormWork NormWork
		{
			get
			{
				return this._NormWork.Entity;
			}
			set
			{
				NormWork previousValue = this._NormWork.Entity;
				if (((previousValue != value) 
							|| (this._NormWork.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NormWork.Entity = null;
						previousValue.NormDetails.Remove(this);
					}
					this._NormWork.Entity = value;
					if ((value != null))
					{
						value.NormDetails.Add(this);
						this._NormWork_ID = value.ID;
					}
					else
					{
						this._NormWork_ID = default(string);
					}
					this.SendPropertyChanged("NormWork");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UnitPrice_NormDetail", Storage="_UnitPrice", ThisKey="UnitPrice_ID", OtherKey="ID", IsForeignKey=true)]
		public UnitPrice UnitPrice
		{
			get
			{
				return this._UnitPrice.Entity;
			}
			set
			{
				UnitPrice previousValue = this._UnitPrice.Entity;
				if (((previousValue != value) 
							|| (this._UnitPrice.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UnitPrice.Entity = null;
						previousValue.NormDetails.Remove(this);
					}
					this._UnitPrice.Entity = value;
					if ((value != null))
					{
						value.NormDetails.Add(this);
						this._UnitPrice_ID = value.ID;
					}
					else
					{
						this._UnitPrice_ID = default(string);
					}
					this.SendPropertyChanged("UnitPrice");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NormWorks")]
	public partial class NormWork : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _Name;
		
		private string _Unit;
		
		private EntitySet<NormDetail> _NormDetails;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnUnitChanging(string value);
    partial void OnUnitChanged();
    #endregion
		
		public NormWork()
		{
			this._NormDetails = new EntitySet<NormDetail>(new Action<NormDetail>(this.attach_NormDetails), new Action<NormDetail>(this.detach_NormDetails));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Unit
		{
			get
			{
				return this._Unit;
			}
			set
			{
				if ((this._Unit != value))
				{
					this.OnUnitChanging(value);
					this.SendPropertyChanging();
					this._Unit = value;
					this.SendPropertyChanged("Unit");
					this.OnUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NormWork_NormDetail", Storage="_NormDetails", ThisKey="ID", OtherKey="NormWork_ID")]
		public EntitySet<NormDetail> NormDetails
		{
			get
			{
				return this._NormDetails;
			}
			set
			{
				this._NormDetails.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NormDetails(NormDetail entity)
		{
			this.SendPropertyChanging();
			entity.NormWork = this;
		}
		
		private void detach_NormDetails(NormDetail entity)
		{
			this.SendPropertyChanging();
			entity.NormWork = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UnitPrice")]
	public partial class UnitPrice : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _Name;
		
		private string _Unit;
		
		private EntitySet<NormDetail> _NormDetails;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnUnitChanging(string value);
    partial void OnUnitChanged();
    #endregion
		
		public UnitPrice()
		{
			this._NormDetails = new EntitySet<NormDetail>(new Action<NormDetail>(this.attach_NormDetails), new Action<NormDetail>(this.detach_NormDetails));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Unit
		{
			get
			{
				return this._Unit;
			}
			set
			{
				if ((this._Unit != value))
				{
					this.OnUnitChanging(value);
					this.SendPropertyChanging();
					this._Unit = value;
					this.SendPropertyChanged("Unit");
					this.OnUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UnitPrice_NormDetail", Storage="_NormDetails", ThisKey="ID", OtherKey="UnitPrice_ID")]
		public EntitySet<NormDetail> NormDetails
		{
			get
			{
				return this._NormDetails;
			}
			set
			{
				this._NormDetails.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NormDetails(NormDetail entity)
		{
			this.SendPropertyChanging();
			entity.UnitPrice = this;
		}
		
		private void detach_NormDetails(NormDetail entity)
		{
			this.SendPropertyChanging();
			entity.UnitPrice = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UnitPrice_Area")]
	public partial class UnitPrice_Area
	{
		
		private string _UnitPrice_ID;
		
		private long _Area_ID;
		
		private System.Nullable<decimal> _Price;
		
		public UnitPrice_Area()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitPrice_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UnitPrice_ID
		{
			get
			{
				return this._UnitPrice_ID;
			}
			set
			{
				if ((this._UnitPrice_ID != value))
				{
					this._UnitPrice_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area_ID", DbType="BigInt NOT NULL")]
		public long Area_ID
		{
			get
			{
				return this._Area_ID;
			}
			set
			{
				if ((this._Area_ID != value))
				{
					this._Area_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Email;
		
		private string _Password;
		
		private string _Last_Name;
		
		private string _First_Name;
		
		private string _Phone;
		
		private string _Workplace;
		
		private string _City;
		
		private string _Url_Image;
		
		private string _Role;
		
		private EntitySet<Building> _Buildings;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnLast_NameChanging(string value);
    partial void OnLast_NameChanged();
    partial void OnFirst_NameChanging(string value);
    partial void OnFirst_NameChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnWorkplaceChanging(string value);
    partial void OnWorkplaceChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnUrl_ImageChanging(string value);
    partial void OnUrl_ImageChanged();
    partial void OnRoleChanging(string value);
    partial void OnRoleChanged();
    #endregion
		
		public User()
		{
			this._Buildings = new EntitySet<Building>(new Action<Building>(this.attach_Buildings), new Action<Building>(this.detach_Buildings));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Last_Name
		{
			get
			{
				return this._Last_Name;
			}
			set
			{
				if ((this._Last_Name != value))
				{
					this.OnLast_NameChanging(value);
					this.SendPropertyChanging();
					this._Last_Name = value;
					this.SendPropertyChanged("Last_Name");
					this.OnLast_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_First_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string First_Name
		{
			get
			{
				return this._First_Name;
			}
			set
			{
				if ((this._First_Name != value))
				{
					this.OnFirst_NameChanging(value);
					this.SendPropertyChanging();
					this._First_Name = value;
					this.SendPropertyChanged("First_Name");
					this.OnFirst_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(12)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Workplace", DbType="NVarChar(100)")]
		public string Workplace
		{
			get
			{
				return this._Workplace;
			}
			set
			{
				if ((this._Workplace != value))
				{
					this.OnWorkplaceChanging(value);
					this.SendPropertyChanging();
					this._Workplace = value;
					this.SendPropertyChanged("Workplace");
					this.OnWorkplaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(50)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url_Image", DbType="NVarChar(500)")]
		public string Url_Image
		{
			get
			{
				return this._Url_Image;
			}
			set
			{
				if ((this._Url_Image != value))
				{
					this.OnUrl_ImageChanging(value);
					this.SendPropertyChanging();
					this._Url_Image = value;
					this.SendPropertyChanged("Url_Image");
					this.OnUrl_ImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this.OnRoleChanging(value);
					this.SendPropertyChanging();
					this._Role = value;
					this.SendPropertyChanged("Role");
					this.OnRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Building", Storage="_Buildings", ThisKey="Email", OtherKey="Email")]
		public EntitySet<Building> Buildings
		{
			get
			{
				return this._Buildings;
			}
			set
			{
				this._Buildings.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Buildings(Building entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_Buildings(Building entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
	}
}
#pragma warning restore 1591
