#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Du_Toan_Xay_Dung.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DTXD")]
	public partial class DataDTXDDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChiTiet_DinhMuc(ChiTiet_DinhMuc instance);
    partial void UpdateChiTiet_DinhMuc(ChiTiet_DinhMuc instance);
    partial void DeleteChiTiet_DinhMuc(ChiTiet_DinhMuc instance);
    partial void InsertCongTrinh(CongTrinh instance);
    partial void UpdateCongTrinh(CongTrinh instance);
    partial void DeleteCongTrinh(CongTrinh instance);
    partial void InsertCongViec(CongViec instance);
    partial void UpdateCongViec(CongViec instance);
    partial void DeleteCongViec(CongViec instance);
    partial void InsertDinhMuc(DinhMuc instance);
    partial void UpdateDinhMuc(DinhMuc instance);
    partial void DeleteDinhMuc(DinhMuc instance);
    partial void InsertDonGia(DonGia instance);
    partial void UpdateDonGia(DonGia instance);
    partial void DeleteDonGia(DonGia instance);
    partial void InsertHangMuc(HangMuc instance);
    partial void UpdateHangMuc(HangMuc instance);
    partial void DeleteHangMuc(HangMuc instance);
    partial void InsertImages_CongTrinh(Images_CongTrinh instance);
    partial void UpdateImages_CongTrinh(Images_CongTrinh instance);
    partial void DeleteImages_CongTrinh(Images_CongTrinh instance);
    partial void InsertNguoi_Dung(Nguoi_Dung instance);
    partial void UpdateNguoi_Dung(Nguoi_Dung instance);
    partial void DeleteNguoi_Dung(Nguoi_Dung instance);
    partial void InsertThanhPhanHaoPhi(ThanhPhanHaoPhi instance);
    partial void UpdateThanhPhanHaoPhi(ThanhPhanHaoPhi instance);
    partial void DeleteThanhPhanHaoPhi(ThanhPhanHaoPhi instance);
    #endregion
		
		public DataDTXDDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DTXDConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataDTXDDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDTXDDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDTXDDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDTXDDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChiTiet_DinhMuc> ChiTiet_DinhMucs
		{
			get
			{
				return this.GetTable<ChiTiet_DinhMuc>();
			}
		}
		
		public System.Data.Linq.Table<CongTrinh> CongTrinhs
		{
			get
			{
				return this.GetTable<CongTrinh>();
			}
		}
		
		public System.Data.Linq.Table<CongViec> CongViecs
		{
			get
			{
				return this.GetTable<CongViec>();
			}
		}
		
		public System.Data.Linq.Table<DinhMuc> DinhMucs
		{
			get
			{
				return this.GetTable<DinhMuc>();
			}
		}
		
		public System.Data.Linq.Table<DonGia> DonGias
		{
			get
			{
				return this.GetTable<DonGia>();
			}
		}
		
		public System.Data.Linq.Table<HangMuc> HangMucs
		{
			get
			{
				return this.GetTable<HangMuc>();
			}
		}
		
		public System.Data.Linq.Table<Images_CongTrinh> Images_CongTrinhs
		{
			get
			{
				return this.GetTable<Images_CongTrinh>();
			}
		}
		
		public System.Data.Linq.Table<Nguoi_Dung> Nguoi_Dungs
		{
			get
			{
				return this.GetTable<Nguoi_Dung>();
			}
		}
		
		public System.Data.Linq.Table<ThanhPhanHaoPhi> ThanhPhanHaoPhis
		{
			get
			{
				return this.GetTable<ThanhPhanHaoPhi>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTiet_DinhMuc")]
	public partial class ChiTiet_DinhMuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _MaHieuCV_DM;
		
		private string _MaVL_NC_MTC;
		
		private decimal _SoLuong;
		
		private string _DonVi;
		
		private EntityRef<DinhMuc> _DinhMuc;
		
		private EntityRef<DonGia> _DonGia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnMaHieuCV_DMChanging(string value);
    partial void OnMaHieuCV_DMChanged();
    partial void OnMaVL_NC_MTCChanging(string value);
    partial void OnMaVL_NC_MTCChanged();
    partial void OnSoLuongChanging(decimal value);
    partial void OnSoLuongChanged();
    partial void OnDonViChanging(string value);
    partial void OnDonViChanged();
    #endregion
		
		public ChiTiet_DinhMuc()
		{
			this._DinhMuc = default(EntityRef<DinhMuc>);
			this._DonGia = default(EntityRef<DonGia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHieuCV_DM", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaHieuCV_DM
		{
			get
			{
				return this._MaHieuCV_DM;
			}
			set
			{
				if ((this._MaHieuCV_DM != value))
				{
					if (this._DinhMuc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHieuCV_DMChanging(value);
					this.SendPropertyChanging();
					this._MaHieuCV_DM = value;
					this.SendPropertyChanged("MaHieuCV_DM");
					this.OnMaHieuCV_DMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaVL_NC_MTC", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaVL_NC_MTC
		{
			get
			{
				return this._MaVL_NC_MTC;
			}
			set
			{
				if ((this._MaVL_NC_MTC != value))
				{
					if (this._DonGia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaVL_NC_MTCChanging(value);
					this.SendPropertyChanging();
					this._MaVL_NC_MTC = value;
					this.SendPropertyChanged("MaVL_NC_MTC");
					this.OnMaVL_NC_MTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Decimal(18,3) NOT NULL")]
		public decimal SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonVi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DonVi
		{
			get
			{
				return this._DonVi;
			}
			set
			{
				if ((this._DonVi != value))
				{
					this.OnDonViChanging(value);
					this.SendPropertyChanging();
					this._DonVi = value;
					this.SendPropertyChanged("DonVi");
					this.OnDonViChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DinhMuc_ChiTiet_DinhMuc", Storage="_DinhMuc", ThisKey="MaHieuCV_DM", OtherKey="MaHieuCV_DM", IsForeignKey=true)]
		public DinhMuc DinhMuc
		{
			get
			{
				return this._DinhMuc.Entity;
			}
			set
			{
				DinhMuc previousValue = this._DinhMuc.Entity;
				if (((previousValue != value) 
							|| (this._DinhMuc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DinhMuc.Entity = null;
						previousValue.ChiTiet_DinhMucs.Remove(this);
					}
					this._DinhMuc.Entity = value;
					if ((value != null))
					{
						value.ChiTiet_DinhMucs.Add(this);
						this._MaHieuCV_DM = value.MaHieuCV_DM;
					}
					else
					{
						this._MaHieuCV_DM = default(string);
					}
					this.SendPropertyChanged("DinhMuc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonGia_ChiTiet_DinhMuc", Storage="_DonGia", ThisKey="MaVL_NC_MTC", OtherKey="MaVL_NC_MTC", IsForeignKey=true)]
		public DonGia DonGia
		{
			get
			{
				return this._DonGia.Entity;
			}
			set
			{
				DonGia previousValue = this._DonGia.Entity;
				if (((previousValue != value) 
							|| (this._DonGia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DonGia.Entity = null;
						previousValue.ChiTiet_DinhMucs.Remove(this);
					}
					this._DonGia.Entity = value;
					if ((value != null))
					{
						value.ChiTiet_DinhMucs.Add(this);
						this._MaVL_NC_MTC = value.MaVL_NC_MTC;
					}
					else
					{
						this._MaVL_NC_MTC = default(string);
					}
					this.SendPropertyChanged("DonGia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CongTrinh")]
	public partial class CongTrinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _MaCT;
		
		private string _Email;
		
		private string _TenCT;
		
		private string _MoTa;
		
		private string _DiaChi;
		
		private decimal _Gia;
		
		private EntitySet<HangMuc> _HangMucs;
		
		private EntitySet<Images_CongTrinh> _Images_CongTrinhs;
		
		private EntityRef<Nguoi_Dung> _Nguoi_Dung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnMaCTChanging(string value);
    partial void OnMaCTChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTenCTChanging(string value);
    partial void OnTenCTChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnGiaChanging(decimal value);
    partial void OnGiaChanged();
    #endregion
		
		public CongTrinh()
		{
			this._HangMucs = new EntitySet<HangMuc>(new Action<HangMuc>(this.attach_HangMucs), new Action<HangMuc>(this.detach_HangMucs));
			this._Images_CongTrinhs = new EntitySet<Images_CongTrinh>(new Action<Images_CongTrinh>(this.attach_Images_CongTrinhs), new Action<Images_CongTrinh>(this.detach_Images_CongTrinhs));
			this._Nguoi_Dung = default(EntityRef<Nguoi_Dung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCT", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCT
		{
			get
			{
				return this._MaCT;
			}
			set
			{
				if ((this._MaCT != value))
				{
					this.OnMaCTChanging(value);
					this.SendPropertyChanging();
					this._MaCT = value;
					this.SendPropertyChanged("MaCT");
					this.OnMaCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					if (this._Nguoi_Dung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCT", DbType="NVarChar(2000) NOT NULL", CanBeNull=false)]
		public string TenCT
		{
			get
			{
				return this._TenCT;
			}
			set
			{
				if ((this._TenCT != value))
				{
					this.OnTenCTChanging(value);
					this.SendPropertyChanging();
					this._TenCT = value;
					this.SendPropertyChanged("TenCT");
					this.OnTenCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(2000)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(1000)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Decimal(18,0) NOT NULL")]
		public decimal Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CongTrinh_HangMuc", Storage="_HangMucs", ThisKey="MaCT", OtherKey="MaCT")]
		public EntitySet<HangMuc> HangMucs
		{
			get
			{
				return this._HangMucs;
			}
			set
			{
				this._HangMucs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CongTrinh_Images_CongTrinh", Storage="_Images_CongTrinhs", ThisKey="MaCT", OtherKey="MaCT")]
		public EntitySet<Images_CongTrinh> Images_CongTrinhs
		{
			get
			{
				return this._Images_CongTrinhs;
			}
			set
			{
				this._Images_CongTrinhs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nguoi_Dung_CongTrinh", Storage="_Nguoi_Dung", ThisKey="Email", OtherKey="Email", IsForeignKey=true)]
		public Nguoi_Dung Nguoi_Dung
		{
			get
			{
				return this._Nguoi_Dung.Entity;
			}
			set
			{
				Nguoi_Dung previousValue = this._Nguoi_Dung.Entity;
				if (((previousValue != value) 
							|| (this._Nguoi_Dung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Nguoi_Dung.Entity = null;
						previousValue.CongTrinhs.Remove(this);
					}
					this._Nguoi_Dung.Entity = value;
					if ((value != null))
					{
						value.CongTrinhs.Add(this);
						this._Email = value.Email;
					}
					else
					{
						this._Email = default(string);
					}
					this.SendPropertyChanged("Nguoi_Dung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HangMucs(HangMuc entity)
		{
			this.SendPropertyChanging();
			entity.CongTrinh = this;
		}
		
		private void detach_HangMucs(HangMuc entity)
		{
			this.SendPropertyChanging();
			entity.CongTrinh = null;
		}
		
		private void attach_Images_CongTrinhs(Images_CongTrinh entity)
		{
			this.SendPropertyChanging();
			entity.CongTrinh = this;
		}
		
		private void detach_Images_CongTrinhs(Images_CongTrinh entity)
		{
			this.SendPropertyChanging();
			entity.CongTrinh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CongViec")]
	public partial class CongViec : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _MaHieuCV_User;
		
		private string _MaHM;
		
		private string _MaHieuCV_DM;
		
		private string _TenCongViec;
		
		private string _DonVi;
		
		private decimal _KhoiLuong;
		
		private decimal _GiaVL;
		
		private decimal _GiaNC;
		
		private decimal _GiaMTC;
		
		private decimal _ThanhTien;
		
		private EntitySet<ThanhPhanHaoPhi> _ThanhPhanHaoPhis;
		
		private EntityRef<HangMuc> _HangMuc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnMaHieuCV_UserChanging(string value);
    partial void OnMaHieuCV_UserChanged();
    partial void OnMaHMChanging(string value);
    partial void OnMaHMChanged();
    partial void OnMaHieuCV_DMChanging(string value);
    partial void OnMaHieuCV_DMChanged();
    partial void OnTenCongViecChanging(string value);
    partial void OnTenCongViecChanged();
    partial void OnDonViChanging(string value);
    partial void OnDonViChanged();
    partial void OnKhoiLuongChanging(decimal value);
    partial void OnKhoiLuongChanged();
    partial void OnGiaVLChanging(decimal value);
    partial void OnGiaVLChanged();
    partial void OnGiaNCChanging(decimal value);
    partial void OnGiaNCChanged();
    partial void OnGiaMTCChanging(decimal value);
    partial void OnGiaMTCChanged();
    partial void OnThanhTienChanging(decimal value);
    partial void OnThanhTienChanged();
    #endregion
		
		public CongViec()
		{
			this._ThanhPhanHaoPhis = new EntitySet<ThanhPhanHaoPhi>(new Action<ThanhPhanHaoPhi>(this.attach_ThanhPhanHaoPhis), new Action<ThanhPhanHaoPhi>(this.detach_ThanhPhanHaoPhis));
			this._HangMuc = default(EntityRef<HangMuc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHieuCV_User", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHieuCV_User
		{
			get
			{
				return this._MaHieuCV_User;
			}
			set
			{
				if ((this._MaHieuCV_User != value))
				{
					this.OnMaHieuCV_UserChanging(value);
					this.SendPropertyChanging();
					this._MaHieuCV_User = value;
					this.SendPropertyChanged("MaHieuCV_User");
					this.OnMaHieuCV_UserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHM", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaHM
		{
			get
			{
				return this._MaHM;
			}
			set
			{
				if ((this._MaHM != value))
				{
					if (this._HangMuc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHMChanging(value);
					this.SendPropertyChanging();
					this._MaHM = value;
					this.SendPropertyChanged("MaHM");
					this.OnMaHMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHieuCV_DM", DbType="NVarChar(50)")]
		public string MaHieuCV_DM
		{
			get
			{
				return this._MaHieuCV_DM;
			}
			set
			{
				if ((this._MaHieuCV_DM != value))
				{
					this.OnMaHieuCV_DMChanging(value);
					this.SendPropertyChanging();
					this._MaHieuCV_DM = value;
					this.SendPropertyChanged("MaHieuCV_DM");
					this.OnMaHieuCV_DMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCongViec", DbType="NVarChar(3000) NOT NULL", CanBeNull=false)]
		public string TenCongViec
		{
			get
			{
				return this._TenCongViec;
			}
			set
			{
				if ((this._TenCongViec != value))
				{
					this.OnTenCongViecChanging(value);
					this.SendPropertyChanging();
					this._TenCongViec = value;
					this.SendPropertyChanged("TenCongViec");
					this.OnTenCongViecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonVi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DonVi
		{
			get
			{
				return this._DonVi;
			}
			set
			{
				if ((this._DonVi != value))
				{
					this.OnDonViChanging(value);
					this.SendPropertyChanging();
					this._DonVi = value;
					this.SendPropertyChanged("DonVi");
					this.OnDonViChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhoiLuong", DbType="Decimal(18,0) NOT NULL")]
		public decimal KhoiLuong
		{
			get
			{
				return this._KhoiLuong;
			}
			set
			{
				if ((this._KhoiLuong != value))
				{
					this.OnKhoiLuongChanging(value);
					this.SendPropertyChanging();
					this._KhoiLuong = value;
					this.SendPropertyChanged("KhoiLuong");
					this.OnKhoiLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaVL", DbType="Decimal(18,3) NOT NULL")]
		public decimal GiaVL
		{
			get
			{
				return this._GiaVL;
			}
			set
			{
				if ((this._GiaVL != value))
				{
					this.OnGiaVLChanging(value);
					this.SendPropertyChanging();
					this._GiaVL = value;
					this.SendPropertyChanged("GiaVL");
					this.OnGiaVLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaNC", DbType="Decimal(18,3) NOT NULL")]
		public decimal GiaNC
		{
			get
			{
				return this._GiaNC;
			}
			set
			{
				if ((this._GiaNC != value))
				{
					this.OnGiaNCChanging(value);
					this.SendPropertyChanging();
					this._GiaNC = value;
					this.SendPropertyChanged("GiaNC");
					this.OnGiaNCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaMTC", DbType="Decimal(18,3) NOT NULL")]
		public decimal GiaMTC
		{
			get
			{
				return this._GiaMTC;
			}
			set
			{
				if ((this._GiaMTC != value))
				{
					this.OnGiaMTCChanging(value);
					this.SendPropertyChanging();
					this._GiaMTC = value;
					this.SendPropertyChanged("GiaMTC");
					this.OnGiaMTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Decimal(18,3) NOT NULL")]
		public decimal ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this.OnThanhTienChanging(value);
					this.SendPropertyChanging();
					this._ThanhTien = value;
					this.SendPropertyChanged("ThanhTien");
					this.OnThanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CongViec_ThanhPhanHaoPhi", Storage="_ThanhPhanHaoPhis", ThisKey="MaHieuCV_User", OtherKey="MaHieuCV_User")]
		public EntitySet<ThanhPhanHaoPhi> ThanhPhanHaoPhis
		{
			get
			{
				return this._ThanhPhanHaoPhis;
			}
			set
			{
				this._ThanhPhanHaoPhis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HangMuc_CongViec", Storage="_HangMuc", ThisKey="MaHM", OtherKey="MaHM", IsForeignKey=true)]
		public HangMuc HangMuc
		{
			get
			{
				return this._HangMuc.Entity;
			}
			set
			{
				HangMuc previousValue = this._HangMuc.Entity;
				if (((previousValue != value) 
							|| (this._HangMuc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HangMuc.Entity = null;
						previousValue.CongViecs.Remove(this);
					}
					this._HangMuc.Entity = value;
					if ((value != null))
					{
						value.CongViecs.Add(this);
						this._MaHM = value.MaHM;
					}
					else
					{
						this._MaHM = default(string);
					}
					this.SendPropertyChanged("HangMuc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ThanhPhanHaoPhis(ThanhPhanHaoPhi entity)
		{
			this.SendPropertyChanging();
			entity.CongViec = this;
		}
		
		private void detach_ThanhPhanHaoPhis(ThanhPhanHaoPhi entity)
		{
			this.SendPropertyChanging();
			entity.CongViec = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DinhMuc")]
	public partial class DinhMuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHieuCV_DM;
		
		private string _CongTac;
		
		private string _DonVi;
		
		private string _RangBuoc;
		
		private EntitySet<ChiTiet_DinhMuc> _ChiTiet_DinhMucs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHieuCV_DMChanging(string value);
    partial void OnMaHieuCV_DMChanged();
    partial void OnCongTacChanging(string value);
    partial void OnCongTacChanged();
    partial void OnDonViChanging(string value);
    partial void OnDonViChanged();
    partial void OnRangBuocChanging(string value);
    partial void OnRangBuocChanged();
    #endregion
		
		public DinhMuc()
		{
			this._ChiTiet_DinhMucs = new EntitySet<ChiTiet_DinhMuc>(new Action<ChiTiet_DinhMuc>(this.attach_ChiTiet_DinhMucs), new Action<ChiTiet_DinhMuc>(this.detach_ChiTiet_DinhMucs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHieuCV_DM", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHieuCV_DM
		{
			get
			{
				return this._MaHieuCV_DM;
			}
			set
			{
				if ((this._MaHieuCV_DM != value))
				{
					this.OnMaHieuCV_DMChanging(value);
					this.SendPropertyChanging();
					this._MaHieuCV_DM = value;
					this.SendPropertyChanged("MaHieuCV_DM");
					this.OnMaHieuCV_DMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CongTac", DbType="NVarChar(2000) NOT NULL", CanBeNull=false)]
		public string CongTac
		{
			get
			{
				return this._CongTac;
			}
			set
			{
				if ((this._CongTac != value))
				{
					this.OnCongTacChanging(value);
					this.SendPropertyChanging();
					this._CongTac = value;
					this.SendPropertyChanged("CongTac");
					this.OnCongTacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonVi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DonVi
		{
			get
			{
				return this._DonVi;
			}
			set
			{
				if ((this._DonVi != value))
				{
					this.OnDonViChanging(value);
					this.SendPropertyChanging();
					this._DonVi = value;
					this.SendPropertyChanged("DonVi");
					this.OnDonViChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RangBuoc", DbType="NVarChar(2000)")]
		public string RangBuoc
		{
			get
			{
				return this._RangBuoc;
			}
			set
			{
				if ((this._RangBuoc != value))
				{
					this.OnRangBuocChanging(value);
					this.SendPropertyChanging();
					this._RangBuoc = value;
					this.SendPropertyChanged("RangBuoc");
					this.OnRangBuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DinhMuc_ChiTiet_DinhMuc", Storage="_ChiTiet_DinhMucs", ThisKey="MaHieuCV_DM", OtherKey="MaHieuCV_DM")]
		public EntitySet<ChiTiet_DinhMuc> ChiTiet_DinhMucs
		{
			get
			{
				return this._ChiTiet_DinhMucs;
			}
			set
			{
				this._ChiTiet_DinhMucs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTiet_DinhMucs(ChiTiet_DinhMuc entity)
		{
			this.SendPropertyChanging();
			entity.DinhMuc = this;
		}
		
		private void detach_ChiTiet_DinhMucs(ChiTiet_DinhMuc entity)
		{
			this.SendPropertyChanging();
			entity.DinhMuc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DonGia")]
	public partial class DonGia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKV;
		
		private string _MaVL_NC_MTC;
		
		private string _Ten;
		
		private string _DonVi;
		
		private decimal _Gia;
		
		private EntitySet<ChiTiet_DinhMuc> _ChiTiet_DinhMucs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKVChanging(string value);
    partial void OnMaKVChanged();
    partial void OnMaVL_NC_MTCChanging(string value);
    partial void OnMaVL_NC_MTCChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnDonViChanging(string value);
    partial void OnDonViChanged();
    partial void OnGiaChanging(decimal value);
    partial void OnGiaChanged();
    #endregion
		
		public DonGia()
		{
			this._ChiTiet_DinhMucs = new EntitySet<ChiTiet_DinhMuc>(new Action<ChiTiet_DinhMuc>(this.attach_ChiTiet_DinhMucs), new Action<ChiTiet_DinhMuc>(this.detach_ChiTiet_DinhMucs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaKV
		{
			get
			{
				return this._MaKV;
			}
			set
			{
				if ((this._MaKV != value))
				{
					this.OnMaKVChanging(value);
					this.SendPropertyChanging();
					this._MaKV = value;
					this.SendPropertyChanged("MaKV");
					this.OnMaKVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaVL_NC_MTC", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaVL_NC_MTC
		{
			get
			{
				return this._MaVL_NC_MTC;
			}
			set
			{
				if ((this._MaVL_NC_MTC != value))
				{
					this.OnMaVL_NC_MTCChanging(value);
					this.SendPropertyChanging();
					this._MaVL_NC_MTC = value;
					this.SendPropertyChanged("MaVL_NC_MTC");
					this.OnMaVL_NC_MTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonVi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DonVi
		{
			get
			{
				return this._DonVi;
			}
			set
			{
				if ((this._DonVi != value))
				{
					this.OnDonViChanging(value);
					this.SendPropertyChanging();
					this._DonVi = value;
					this.SendPropertyChanged("DonVi");
					this.OnDonViChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Decimal(18,0) NOT NULL")]
		public decimal Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonGia_ChiTiet_DinhMuc", Storage="_ChiTiet_DinhMucs", ThisKey="MaVL_NC_MTC", OtherKey="MaVL_NC_MTC")]
		public EntitySet<ChiTiet_DinhMuc> ChiTiet_DinhMucs
		{
			get
			{
				return this._ChiTiet_DinhMucs;
			}
			set
			{
				this._ChiTiet_DinhMucs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTiet_DinhMucs(ChiTiet_DinhMuc entity)
		{
			this.SendPropertyChanging();
			entity.DonGia = this;
		}
		
		private void detach_ChiTiet_DinhMucs(ChiTiet_DinhMuc entity)
		{
			this.SendPropertyChanging();
			entity.DonGia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HangMuc")]
	public partial class HangMuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _MaHM;
		
		private string _MaCT;
		
		private string _TenHM;
		
		private string _MoTa;
		
		private decimal _Gia;
		
		private EntitySet<CongViec> _CongViecs;
		
		private EntityRef<CongTrinh> _CongTrinh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnMaHMChanging(string value);
    partial void OnMaHMChanged();
    partial void OnMaCTChanging(string value);
    partial void OnMaCTChanged();
    partial void OnTenHMChanging(string value);
    partial void OnTenHMChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnGiaChanging(decimal value);
    partial void OnGiaChanged();
    #endregion
		
		public HangMuc()
		{
			this._CongViecs = new EntitySet<CongViec>(new Action<CongViec>(this.attach_CongViecs), new Action<CongViec>(this.detach_CongViecs));
			this._CongTrinh = default(EntityRef<CongTrinh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHM", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHM
		{
			get
			{
				return this._MaHM;
			}
			set
			{
				if ((this._MaHM != value))
				{
					this.OnMaHMChanging(value);
					this.SendPropertyChanging();
					this._MaHM = value;
					this.SendPropertyChanged("MaHM");
					this.OnMaHMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCT", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaCT
		{
			get
			{
				return this._MaCT;
			}
			set
			{
				if ((this._MaCT != value))
				{
					if (this._CongTrinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCTChanging(value);
					this.SendPropertyChanging();
					this._MaCT = value;
					this.SendPropertyChanged("MaCT");
					this.OnMaCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHM", DbType="NVarChar(2000) NOT NULL", CanBeNull=false)]
		public string TenHM
		{
			get
			{
				return this._TenHM;
			}
			set
			{
				if ((this._TenHM != value))
				{
					this.OnTenHMChanging(value);
					this.SendPropertyChanging();
					this._TenHM = value;
					this.SendPropertyChanged("TenHM");
					this.OnTenHMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(2000)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Decimal(18,3) NOT NULL")]
		public decimal Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HangMuc_CongViec", Storage="_CongViecs", ThisKey="MaHM", OtherKey="MaHM")]
		public EntitySet<CongViec> CongViecs
		{
			get
			{
				return this._CongViecs;
			}
			set
			{
				this._CongViecs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CongTrinh_HangMuc", Storage="_CongTrinh", ThisKey="MaCT", OtherKey="MaCT", IsForeignKey=true)]
		public CongTrinh CongTrinh
		{
			get
			{
				return this._CongTrinh.Entity;
			}
			set
			{
				CongTrinh previousValue = this._CongTrinh.Entity;
				if (((previousValue != value) 
							|| (this._CongTrinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CongTrinh.Entity = null;
						previousValue.HangMucs.Remove(this);
					}
					this._CongTrinh.Entity = value;
					if ((value != null))
					{
						value.HangMucs.Add(this);
						this._MaCT = value.MaCT;
					}
					else
					{
						this._MaCT = default(string);
					}
					this.SendPropertyChanged("CongTrinh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CongViecs(CongViec entity)
		{
			this.SendPropertyChanging();
			entity.HangMuc = this;
		}
		
		private void detach_CongViecs(CongViec entity)
		{
			this.SendPropertyChanging();
			entity.HangMuc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Images_CongTrinh")]
	public partial class Images_CongTrinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _MaCT;
		
		private string _Url;
		
		private EntityRef<CongTrinh> _CongTrinh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnMaCTChanging(string value);
    partial void OnMaCTChanged();
    partial void OnUrlChanging(string value);
    partial void OnUrlChanged();
    #endregion
		
		public Images_CongTrinh()
		{
			this._CongTrinh = default(EntityRef<CongTrinh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCT", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaCT
		{
			get
			{
				return this._MaCT;
			}
			set
			{
				if ((this._MaCT != value))
				{
					if (this._CongTrinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCTChanging(value);
					this.SendPropertyChanging();
					this._MaCT = value;
					this.SendPropertyChanged("MaCT");
					this.OnMaCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this.OnUrlChanging(value);
					this.SendPropertyChanging();
					this._Url = value;
					this.SendPropertyChanged("Url");
					this.OnUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CongTrinh_Images_CongTrinh", Storage="_CongTrinh", ThisKey="MaCT", OtherKey="MaCT", IsForeignKey=true)]
		public CongTrinh CongTrinh
		{
			get
			{
				return this._CongTrinh.Entity;
			}
			set
			{
				CongTrinh previousValue = this._CongTrinh.Entity;
				if (((previousValue != value) 
							|| (this._CongTrinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CongTrinh.Entity = null;
						previousValue.Images_CongTrinhs.Remove(this);
					}
					this._CongTrinh.Entity = value;
					if ((value != null))
					{
						value.Images_CongTrinhs.Add(this);
						this._MaCT = value.MaCT;
					}
					else
					{
						this._MaCT = default(string);
					}
					this.SendPropertyChanged("CongTrinh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nguoi_Dung")]
	public partial class Nguoi_Dung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Email;
		
		private string _MatKhau;
		
		private string _Ho_TenLot;
		
		private string _Ten;
		
		private string _SDT;
		
		private string _NoiLamViec;
		
		private string _ThanhPho;
		
		private string _Url_HinhAnh;
		
		private string _Quyen;
		
		private EntitySet<CongTrinh> _CongTrinhs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnHo_TenLotChanging(string value);
    partial void OnHo_TenLotChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnNoiLamViecChanging(string value);
    partial void OnNoiLamViecChanged();
    partial void OnThanhPhoChanging(string value);
    partial void OnThanhPhoChanged();
    partial void OnUrl_HinhAnhChanging(string value);
    partial void OnUrl_HinhAnhChanged();
    partial void OnQuyenChanging(string value);
    partial void OnQuyenChanged();
    #endregion
		
		public Nguoi_Dung()
		{
			this._CongTrinhs = new EntitySet<CongTrinh>(new Action<CongTrinh>(this.attach_CongTrinhs), new Action<CongTrinh>(this.detach_CongTrinhs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ho_TenLot", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Ho_TenLot
		{
			get
			{
				return this._Ho_TenLot;
			}
			set
			{
				if ((this._Ho_TenLot != value))
				{
					this.OnHo_TenLotChanging(value);
					this.SendPropertyChanging();
					this._Ho_TenLot = value;
					this.SendPropertyChanged("Ho_TenLot");
					this.OnHo_TenLotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(12)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiLamViec", DbType="NVarChar(100)")]
		public string NoiLamViec
		{
			get
			{
				return this._NoiLamViec;
			}
			set
			{
				if ((this._NoiLamViec != value))
				{
					this.OnNoiLamViecChanging(value);
					this.SendPropertyChanging();
					this._NoiLamViec = value;
					this.SendPropertyChanged("NoiLamViec");
					this.OnNoiLamViecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhPho", DbType="NVarChar(50)")]
		public string ThanhPho
		{
			get
			{
				return this._ThanhPho;
			}
			set
			{
				if ((this._ThanhPho != value))
				{
					this.OnThanhPhoChanging(value);
					this.SendPropertyChanging();
					this._ThanhPho = value;
					this.SendPropertyChanged("ThanhPho");
					this.OnThanhPhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url_HinhAnh", DbType="NVarChar(500)")]
		public string Url_HinhAnh
		{
			get
			{
				return this._Url_HinhAnh;
			}
			set
			{
				if ((this._Url_HinhAnh != value))
				{
					this.OnUrl_HinhAnhChanging(value);
					this.SendPropertyChanging();
					this._Url_HinhAnh = value;
					this.SendPropertyChanged("Url_HinhAnh");
					this.OnUrl_HinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quyen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Quyen
		{
			get
			{
				return this._Quyen;
			}
			set
			{
				if ((this._Quyen != value))
				{
					this.OnQuyenChanging(value);
					this.SendPropertyChanging();
					this._Quyen = value;
					this.SendPropertyChanged("Quyen");
					this.OnQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nguoi_Dung_CongTrinh", Storage="_CongTrinhs", ThisKey="Email", OtherKey="Email")]
		public EntitySet<CongTrinh> CongTrinhs
		{
			get
			{
				return this._CongTrinhs;
			}
			set
			{
				this._CongTrinhs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CongTrinhs(CongTrinh entity)
		{
			this.SendPropertyChanging();
			entity.Nguoi_Dung = this;
		}
		
		private void detach_CongTrinhs(CongTrinh entity)
		{
			this.SendPropertyChanging();
			entity.Nguoi_Dung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThanhPhanHaoPhi")]
	public partial class ThanhPhanHaoPhi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _MaHP;
		
		private string _MaHieuCV_User;
		
		private string _Ten;
		
		private string _DonVi;
		
		private decimal _SoLuong_DM;
		
		private decimal _Gia;
		
		private EntityRef<CongViec> _CongViec;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnMaHPChanging(string value);
    partial void OnMaHPChanged();
    partial void OnMaHieuCV_UserChanging(string value);
    partial void OnMaHieuCV_UserChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnDonViChanging(string value);
    partial void OnDonViChanged();
    partial void OnSoLuong_DMChanging(decimal value);
    partial void OnSoLuong_DMChanged();
    partial void OnGiaChanging(decimal value);
    partial void OnGiaChanged();
    #endregion
		
		public ThanhPhanHaoPhi()
		{
			this._CongViec = default(EntityRef<CongViec>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHP", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHP
		{
			get
			{
				return this._MaHP;
			}
			set
			{
				if ((this._MaHP != value))
				{
					this.OnMaHPChanging(value);
					this.SendPropertyChanging();
					this._MaHP = value;
					this.SendPropertyChanged("MaHP");
					this.OnMaHPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHieuCV_User", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaHieuCV_User
		{
			get
			{
				return this._MaHieuCV_User;
			}
			set
			{
				if ((this._MaHieuCV_User != value))
				{
					if (this._CongViec.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHieuCV_UserChanging(value);
					this.SendPropertyChanging();
					this._MaHieuCV_User = value;
					this.SendPropertyChanged("MaHieuCV_User");
					this.OnMaHieuCV_UserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(2000) NOT NULL", CanBeNull=false)]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonVi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DonVi
		{
			get
			{
				return this._DonVi;
			}
			set
			{
				if ((this._DonVi != value))
				{
					this.OnDonViChanging(value);
					this.SendPropertyChanging();
					this._DonVi = value;
					this.SendPropertyChanged("DonVi");
					this.OnDonViChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong_DM", DbType="Decimal(18,3) NOT NULL")]
		public decimal SoLuong_DM
		{
			get
			{
				return this._SoLuong_DM;
			}
			set
			{
				if ((this._SoLuong_DM != value))
				{
					this.OnSoLuong_DMChanging(value);
					this.SendPropertyChanging();
					this._SoLuong_DM = value;
					this.SendPropertyChanged("SoLuong_DM");
					this.OnSoLuong_DMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Decimal(18,3) NOT NULL")]
		public decimal Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CongViec_ThanhPhanHaoPhi", Storage="_CongViec", ThisKey="MaHieuCV_User", OtherKey="MaHieuCV_User", IsForeignKey=true)]
		public CongViec CongViec
		{
			get
			{
				return this._CongViec.Entity;
			}
			set
			{
				CongViec previousValue = this._CongViec.Entity;
				if (((previousValue != value) 
							|| (this._CongViec.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CongViec.Entity = null;
						previousValue.ThanhPhanHaoPhis.Remove(this);
					}
					this._CongViec.Entity = value;
					if ((value != null))
					{
						value.ThanhPhanHaoPhis.Add(this);
						this._MaHieuCV_User = value.MaHieuCV_User;
					}
					else
					{
						this._MaHieuCV_User = default(string);
					}
					this.SendPropertyChanged("CongViec");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
